language: python
python:
  - '2.7'
  - '3.4'
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install pylint; pip install -r src/client/requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then pip3 install pylint; pip3 install -r src/client/requirements.txt; fi
# command to run tests
script: pylint src/client/cassh -d redefined-builtin -d useless-object-inheritance
